### ISSUE TITLE
change with console or powercli

### ISSUE THREAD

**Issue by csabyka** [pfoo/zabbix-esxi#2]
**esxi console:** 
_Listing:_ 
vim-cmd hostsvc/advopt/view Config.HostAgent.plugins.solo.enableMob
_Enable:_
vim-cmd hostsvc/advopt/update Config.HostAgent.plugins.solo.enableMob bool true
_Disable:_
vim-cmd hostsvc/advopt/update Config.HostAgent.plugins.solo.enableMob bool false

**Powercli:** 
_Listing:_
Get-VMHost **#IPADDRESS** | Get-VmHostAdvancedConfiguration -Name Config.HostAgent.plugins.solo.enableMob | Format-List
_Enable:_
Get-VMHost **#IPADDRESS** | Set-VMHostAdvancedConfiguration -Name Config.HostAgent.plugins.solo.enableMob  -Value True
_Disable:_
Get-VMHost **#IPADDRESS** | Set-VMHostAdvancedConfiguration -Name Config.HostAgent.plugins.solo.enableMob  -Value False

**Comment by pfoo** [comment]
Thanks !
