### ISSUE TITLE
unkown virtual machine uuid

### ISSUE THREAD

**Issue by Kawabountou** [pfoo/zabbix-esxi#4]
Hi,

When i use your template (and other template on VMWARE), I have this error message : unknow virtual machine uuid.

I have no more information on this.

Have you an explication? 

Thank for your help

**Comment by timrsa** [comment]
I also had issues because I tried to use the esxcli system uuid get command, which gave me a UUID but the wrong one, you need to follow the method stated in the read me. If you do this it works flawlessly.
